export const routeMap = {
    "main": "/",
    "contests": "/contests/",
    "info": "/info/",
    "archive": "/archive/",
    "submissions": "/problemset/status/",
    "problems": "/problemset/main/",
    "submission": "/submission/:id/",
    "profile": "/user/profile/:user/",
    "profileSubmissions": "/user/profile/:user/submissions/",
    "profileSettings": "/user/profile/:user/settings/",
    "problem": "/problemset/main/:problem/",
    "problemSubmit": "/problemset/main/:problem/submit/",
    "problemSubmissions": "/problemset/main/:problem/submissions/",
    "problemRanklist": "/problemset/main/:problem/ranklist/",
    "login": "/user/login/",
    "register": "/user/register/",
}