// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Judges            string
	Partials          string
	ProblemCategories string
	ProblemRels       string
	Submissions       string
	Users             string
}{
	Judges:            "judges",
	Partials:          "partials",
	ProblemCategories: "problem_categories",
	ProblemRels:       "problem_rels",
	Submissions:       "submissions",
	Users:             "users",
}
