// Code generated by SQLBoiler 4.3.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSubmissions(t *testing.T) {
	t.Parallel()

	query := Submissions()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSubmissionsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Submission{}
	if err = randomize.Struct(seed, o, submissionDBTypes, true, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Submissions().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSubmissionsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Submission{}
	if err = randomize.Struct(seed, o, submissionDBTypes, true, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Submissions().DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Submissions().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSubmissionsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Submission{}
	if err = randomize.Struct(seed, o, submissionDBTypes, true, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SubmissionSlice{o}

	if rowsAff, err := slice.DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Submissions().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSubmissionsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Submission{}
	if err = randomize.Struct(seed, o, submissionDBTypes, true, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SubmissionExists(tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Submission exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SubmissionExists to return true, but got false.")
	}
}

func testSubmissionsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Submission{}
	if err = randomize.Struct(seed, o, submissionDBTypes, true, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	submissionFound, err := FindSubmission(tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if submissionFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSubmissionsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Submission{}
	if err = randomize.Struct(seed, o, submissionDBTypes, true, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Submissions().Bind(nil, tx, o); err != nil {
		t.Error(err)
	}
}

func testSubmissionsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Submission{}
	if err = randomize.Struct(seed, o, submissionDBTypes, true, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Submissions().One(tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSubmissionsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	submissionOne := &Submission{}
	submissionTwo := &Submission{}
	if err = randomize.Struct(seed, submissionOne, submissionDBTypes, false, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}
	if err = randomize.Struct(seed, submissionTwo, submissionDBTypes, false, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = submissionOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = submissionTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Submissions().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSubmissionsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	submissionOne := &Submission{}
	submissionTwo := &Submission{}
	if err = randomize.Struct(seed, submissionOne, submissionDBTypes, false, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}
	if err = randomize.Struct(seed, submissionTwo, submissionDBTypes, false, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = submissionOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = submissionTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Submissions().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func submissionBeforeInsertHook(e boil.Executor, o *Submission) error {
	*o = Submission{}
	return nil
}

func submissionAfterInsertHook(e boil.Executor, o *Submission) error {
	*o = Submission{}
	return nil
}

func submissionAfterSelectHook(e boil.Executor, o *Submission) error {
	*o = Submission{}
	return nil
}

func submissionBeforeUpdateHook(e boil.Executor, o *Submission) error {
	*o = Submission{}
	return nil
}

func submissionAfterUpdateHook(e boil.Executor, o *Submission) error {
	*o = Submission{}
	return nil
}

func submissionBeforeDeleteHook(e boil.Executor, o *Submission) error {
	*o = Submission{}
	return nil
}

func submissionAfterDeleteHook(e boil.Executor, o *Submission) error {
	*o = Submission{}
	return nil
}

func submissionBeforeUpsertHook(e boil.Executor, o *Submission) error {
	*o = Submission{}
	return nil
}

func submissionAfterUpsertHook(e boil.Executor, o *Submission) error {
	*o = Submission{}
	return nil
}

func testSubmissionsHooks(t *testing.T) {
	t.Parallel()

	var err error

	empty := &Submission{}
	o := &Submission{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, submissionDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Submission object: %s", err)
	}

	AddSubmissionHook(boil.BeforeInsertHook, submissionBeforeInsertHook)
	if err = o.doBeforeInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	submissionBeforeInsertHooks = []SubmissionHook{}

	AddSubmissionHook(boil.AfterInsertHook, submissionAfterInsertHook)
	if err = o.doAfterInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	submissionAfterInsertHooks = []SubmissionHook{}

	AddSubmissionHook(boil.AfterSelectHook, submissionAfterSelectHook)
	if err = o.doAfterSelectHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	submissionAfterSelectHooks = []SubmissionHook{}

	AddSubmissionHook(boil.BeforeUpdateHook, submissionBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	submissionBeforeUpdateHooks = []SubmissionHook{}

	AddSubmissionHook(boil.AfterUpdateHook, submissionAfterUpdateHook)
	if err = o.doAfterUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	submissionAfterUpdateHooks = []SubmissionHook{}

	AddSubmissionHook(boil.BeforeDeleteHook, submissionBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	submissionBeforeDeleteHooks = []SubmissionHook{}

	AddSubmissionHook(boil.AfterDeleteHook, submissionAfterDeleteHook)
	if err = o.doAfterDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	submissionAfterDeleteHooks = []SubmissionHook{}

	AddSubmissionHook(boil.BeforeUpsertHook, submissionBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	submissionBeforeUpsertHooks = []SubmissionHook{}

	AddSubmissionHook(boil.AfterUpsertHook, submissionAfterUpsertHook)
	if err = o.doAfterUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	submissionAfterUpsertHooks = []SubmissionHook{}
}

func testSubmissionsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Submission{}
	if err = randomize.Struct(seed, o, submissionDBTypes, true, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Submissions().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSubmissionsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Submission{}
	if err = randomize.Struct(seed, o, submissionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Whitelist(submissionColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Submissions().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSubmissionToOneUserUsingUser(t *testing.T) {

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var local Submission
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, submissionDBTypes, false, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := SubmissionSlice{&local}
	if err = local.L.LoadUser(tx, false, (*[]*Submission)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testSubmissionToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a Submission
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, submissionDBTypes, false, strmangle.SetComplement(submissionPrimaryKeyColumns, submissionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Submissions[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testSubmissionsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Submission{}
	if err = randomize.Struct(seed, o, submissionDBTypes, true, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testSubmissionsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Submission{}
	if err = randomize.Struct(seed, o, submissionDBTypes, true, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SubmissionSlice{o}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}

func testSubmissionsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Submission{}
	if err = randomize.Struct(seed, o, submissionDBTypes, true, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Submissions().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	submissionDBTypes = map[string]string{`ID`: `integer`, `Status`: `text`, `Ontest`: `text`, `UserID`: `integer`, `Problemset`: `text`, `Problem`: `text`, `Language`: `text`, `Private`: `boolean`, `Verdict`: `integer`, `Source`: `bytea`, `Started`: `boolean`, `Submitted`: `timestamp with time zone`, `Judged`: `timestamp with time zone`}
	_                 = bytes.MinRead
)

func testSubmissionsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(submissionPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(submissionAllColumns) == len(submissionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Submission{}
	if err = randomize.Struct(seed, o, submissionDBTypes, true, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Submissions().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, submissionDBTypes, true, submissionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	if rowsAff, err := o.Update(tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSubmissionsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(submissionAllColumns) == len(submissionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Submission{}
	if err = randomize.Struct(seed, o, submissionDBTypes, true, submissionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Submissions().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, submissionDBTypes, true, submissionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(submissionAllColumns, submissionPrimaryKeyColumns) {
		fields = submissionAllColumns
	} else {
		fields = strmangle.SetComplement(
			submissionAllColumns,
			submissionPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SubmissionSlice{o}
	if rowsAff, err := slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSubmissionsUpsert(t *testing.T) {
	t.Parallel()

	if len(submissionAllColumns) == len(submissionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Submission{}
	if err = randomize.Struct(seed, &o, submissionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Submission: %s", err)
	}

	count, err := Submissions().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, submissionDBTypes, false, submissionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Submission struct: %s", err)
	}

	if err = o.Upsert(tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Submission: %s", err)
	}

	count, err = Submissions().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
