// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"hu_HU": &dictionary{index: hu_HUIndex, data: hu_HUData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%s's profile":            45,
	"%s's submissions":        46,
	"Accepted":                0,
	"Activate your account":   38,
	"Add":                     75,
	"Add a tag to problem %q": 73,
	"Admin":                   52,
	"An email with further instructions was sent to the given address (if it's registered in our system).": 23,
	"Archive":                               14,
	"Attachments":                           76,
	"Attempted problems":                    96,
	"Author":                                70,
	"Can't logout if you've not logged in.": 32,
	"Cancel":                                74,
	"Category":                              88,
	"Change":                                100,
	"Checker output":                        108,
	"Clear":                                 92,
	"Close":                                 60,
	"Code":                                  86,
	"Compilation error":                     10,
	"Date":                                  114,
	"Didn't run":                            6,
	"Edit":                                  78,
	"Email":                                 122,
	"Expected output":                       107,
	"Fastest":                               79,
	"File":                                  77,
	"Filter":                                90,
	"Filter author?":                        91,
	"Forgot password?":                      119,
	"Home":                                  125,
	"IO files":                              66,
	"Identifier":                            62,
	"Information":                           61,
	"Internal error":                        5,
	"Invalid authentication token.":         31,
	"Invalid key provided.":                 24,
	"It's required to give a new password.": 48,
	"Language":                              87,
	"Last submissions":                      72,
	"Least memory":                          82,
	"Login":                                 120,
	"Logout":                                53,
	"Memory":                                104,
	"Memory limit":                          65,
	"Memory limit exceeded":                 4,
	"Name":                                  80,
	"New password":                          98,
	"New password again":                    99,
	"Nickname":                              117,
	"No category":                           19,
	"Old password":                          97,
	"Partially correct":                     7,
	"Password":                              118,
	"Password again":                        121,
	"Password changed successfully! You can login with your new password.": 26,
	"Password reset":                  22,
	"Points":                          94,
	"Presentation error":              8,
	"Problem":                         85,
	"Problems":                        20,
	"Profile":                         50,
	"Program's output":                106,
	"Ranklist":                        59,
	"Register":                        123,
	"Rejudge":                         113,
	"Reset password":                  124,
	"Result":                          81,
	"Results":                         84,
	"Results - %s (%s)":               16,
	"Running":                         11,
	"Runtime error":                   2,
	"Save":                            102,
	"Settings":                        51,
	"Show tags for unsolved problems": 101,
	"Skipped":                         9,
	"Smallest":                        83,
	"Solved problems":                 95,
	"Solvers":                         93,
	"Statement":                       55,
	"Statement - %s (%s)":             15,
	"Submission #%d":                  13,
	"Submissions":                     21,
	"Submissions - %s (%s)":           18,
	"Submit":                          56,
	"Submit - %s (%s)":                17,
	"Submit solution":                 71,
	"Subtask":                         109,
	"Successful activation. You can login now!": 44,
	"Successful login!":                         29,
	"Sum":                                       110,
	"Tags":                                      67,
	"Task type":                                 69,
	"Test":                                      111,
	"Thank you for registering! We've sent you an email with further instructions about finishing your registration.": 41,
	"The account is not activated. Check your emails!":                                                                28,
	"The email field is required.":     36,
	"The email is already registered.": 40,
	"The nickname can only consist of alphanumeric characters: letters (including non-latin characters such as 'á' or 'ű') and digits.": 37,
	"The nickname field is required.":              33,
	"The nickname is already registered.":          39,
	"The password confirmation field is required.": 35,
	"The password field is required.":              34,
	"The two given passwords doesn't match.":       49,
	"The two passwords don't match.":               25,
	"This account has already been activated.":     42,
	"Time":                            105,
	"Time limit":                      64,
	"Time limit exceeded":             3,
	"Title":                           63,
	"Uploaded":                        12,
	"User":                            115,
	"Verdict":                         112,
	"Visible":                         89,
	"We found the following problems": 116,
	"Wrong activation key. Are you sure you've clicked on the right link?": 43,
	"Wrong answer":                1,
	"Wrong credentials.":          30,
	"Wrong old password.":         47,
	"You're already logged in...": 27,
	"accepted":                    58,
	"all":                         57,
	"en":                          54,
	"language":                    127,
	"on test %s":                  103,
	"show":                        68,
	"source":                      126,
}

var en_USIndex = []uint32{ // 129 elements
	// Entry 0 - 1F
	0x00000000, 0x00000009, 0x00000016, 0x00000024,
	0x00000038, 0x0000004e, 0x0000005d, 0x00000068,
	0x0000007a, 0x0000008d, 0x00000095, 0x000000a7,
	0x000000af, 0x000000b8, 0x000000ca, 0x000000d2,
	0x000000ec, 0x00000104, 0x0000011b, 0x00000137,
	0x00000143, 0x0000014c, 0x00000158, 0x00000167,
	0x000001cc, 0x000001e2, 0x00000201, 0x00000246,
	0x00000262, 0x00000293, 0x000002a5, 0x000002b8,
	// Entry 20 - 3F
	0x000002d6, 0x000002fc, 0x0000031c, 0x0000033c,
	0x00000369, 0x00000386, 0x0000040a, 0x00000420,
	0x00000444, 0x00000465, 0x000004d5, 0x000004fe,
	0x00000543, 0x0000056d, 0x0000057d, 0x00000591,
	0x000005a5, 0x000005cb, 0x000005f2, 0x000005fa,
	0x00000603, 0x00000609, 0x00000610, 0x00000613,
	0x0000061d, 0x00000624, 0x00000628, 0x00000631,
	0x0000063a, 0x00000640, 0x0000064c, 0x00000657,
	// Entry 40 - 5F
	0x0000065d, 0x00000668, 0x00000675, 0x0000067e,
	0x00000683, 0x00000688, 0x00000692, 0x00000699,
	0x000006a9, 0x000006ba, 0x000006d5, 0x000006dc,
	0x000006e0, 0x000006ec, 0x000006f1, 0x000006f6,
	0x000006fe, 0x00000703, 0x0000070a, 0x00000717,
	0x00000720, 0x00000728, 0x00000730, 0x00000735,
	0x0000073e, 0x00000747, 0x0000074f, 0x00000756,
	0x00000765, 0x0000076b, 0x00000773, 0x0000077a,
	// Entry 60 - 7F
	0x0000078a, 0x0000079d, 0x000007aa, 0x000007b7,
	0x000007ca, 0x000007d1, 0x000007f1, 0x000007f6,
	0x00000804, 0x0000080b, 0x00000810, 0x00000821,
	0x00000831, 0x00000840, 0x00000848, 0x0000084c,
	0x00000851, 0x00000859, 0x00000861, 0x00000866,
	0x0000086b, 0x0000088b, 0x00000894, 0x0000089d,
	0x000008ae, 0x000008b4, 0x000008c3, 0x000008c9,
	0x000008d2, 0x000008e1, 0x000008e6, 0x000008ed,
	// Entry 80 - 9F
	0x000008f6,
} // Size: 540 bytes

const en_USData string = "" + // Size: 2294 bytes
	"\x02Accepted\x02Wrong answer\x02Runtime error\x02Time limit exceeded\x02" +
	"Memory limit exceeded\x02Internal error\x02Didn't run\x02Partially corre" +
	"ct\x02Presentation error\x02Skipped\x02Compilation error\x02Running\x02U" +
	"ploaded\x02Submission #%[1]d\x02Archive\x02Statement - %[1]s (%[2]s)\x02" +
	"Results - %[1]s (%[2]s)\x02Submit - %[1]s (%[2]s)\x02Submissions - %[1]s" +
	" (%[2]s)\x02No category\x02Problems\x02Submissions\x02Password reset\x02" +
	"An email with further instructions was sent to the given address (if it'" +
	"s registered in our system).\x02Invalid key provided.\x02The two passwor" +
	"ds don't match.\x02Password changed successfully! You can login with you" +
	"r new password.\x02You're already logged in...\x02The account is not act" +
	"ivated. Check your emails!\x02Successful login!\x02Wrong credentials." +
	"\x02Invalid authentication token.\x02Can't logout if you've not logged i" +
	"n.\x02The nickname field is required.\x02The password field is required." +
	"\x02The password confirmation field is required.\x02The email field is r" +
	"equired.\x02The nickname can only consist of alphanumeric characters: le" +
	"tters (including non-latin characters such as 'á' or 'ű') and digits." +
	"\x02Activate your account\x02The nickname is already registered.\x02The " +
	"email is already registered.\x02Thank you for registering! We've sent yo" +
	"u an email with further instructions about finishing your registration." +
	"\x02This account has already been activated.\x02Wrong activation key. Ar" +
	"e you sure you've clicked on the right link?\x02Successful activation. Y" +
	"ou can login now!\x02%[1]s's profile\x02%[1]s's submissions\x02Wrong old" +
	" password.\x02It's required to give a new password.\x02The two given pas" +
	"swords doesn't match.\x02Profile\x02Settings\x02Admin\x02Logout\x02en" +
	"\x02Statement\x02Submit\x02all\x02accepted\x02Ranklist\x02Close\x02Infor" +
	"mation\x02Identifier\x02Title\x02Time limit\x02Memory limit\x02IO files" +
	"\x02Tags\x02show\x02Task type\x02Author\x02Submit solution\x02Last submi" +
	"ssions\x02Add a tag to problem %[1]q\x02Cancel\x02Add\x02Attachments\x02" +
	"File\x02Edit\x02Fastest\x02Name\x02Result\x02Least memory\x02Smallest" +
	"\x02Results\x02Problem\x02Code\x02Language\x02Category\x02Visible\x02Fil" +
	"ter\x02Filter author?\x02Clear\x02Solvers\x02Points\x02Solved problems" +
	"\x02Attempted problems\x02Old password\x02New password\x02New password a" +
	"gain\x02Change\x02Show tags for unsolved problems\x02Save\x02on test %[1" +
	"]s\x02Memory\x02Time\x02Program's output\x02Expected output\x02Checker o" +
	"utput\x02Subtask\x02Sum\x02Test\x02Verdict\x02Rejudge\x02Date\x02User" +
	"\x02We found the following problems\x02Nickname\x02Password\x02Forgot pa" +
	"ssword?\x02Login\x02Password again\x02Email\x02Register\x02Reset passwor" +
	"d\x02Home\x02source\x02language"

var hu_HUIndex = []uint32{ // 129 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000a, 0x00000019, 0x00000026,
	0x0000003c, 0x00000056, 0x00000062, 0x0000006d,
	0x0000007d, 0x00000091, 0x0000009a, 0x000000aa,
	0x000000ae, 0x000000b9, 0x000000cb, 0x000000d5,
	0x000000ee, 0x0000010a, 0x00000125, 0x00000142,
	0x00000153, 0x0000015d, 0x0000016a, 0x0000017e,
	0x000001f5, 0x00000206, 0x0000022f, 0x0000027e,
	0x00000295, 0x000002db, 0x000002ee, 0x00000317,
	// Entry 20 - 3F
	0x00000336, 0x00000356, 0x0000037b, 0x000003a3,
	0x000003d9, 0x00000400, 0x00000495, 0x000004a9,
	0x000004c1, 0x000004e0, 0x00000566, 0x00000586,
	0x000005dc, 0x00000608, 0x00000617, 0x0000062a,
	0x00000643, 0x00000664, 0x0000068d, 0x00000694,
	0x000006a3, 0x000006a9, 0x000006b3, 0x000006b6,
	0x000006bf, 0x000006c7, 0x000006cf, 0x000006da,
	0x000006e6, 0x000006ed, 0x000006fb, 0x00000707,
	// Entry 40 - 5F
	0x0000070c, 0x00000716, 0x00000724, 0x0000072f,
	0x00000735, 0x0000073c, 0x00000743, 0x0000074b,
	0x00000761, 0x00000776, 0x0000079d, 0x000007a4,
	0x000007ad, 0x000007ba, 0x000007c0, 0x000007ca,
	0x000007d6, 0x000007db, 0x000007e5, 0x000007fa,
	0x00000804, 0x00000810, 0x00000818, 0x0000081d,
	0x00000823, 0x0000082e, 0x00000838, 0x00000841,
	0x00000855, 0x0000085d, 0x00000867, 0x0000086e,
	// Entry 60 - 7F
	0x00000882, 0x00000899, 0x000008a7, 0x000008b3,
	0x000008cb, 0x000008d6, 0x000008fe, 0x00000903,
	0x00000914, 0x0000091d, 0x00000922, 0x00000933,
	0x00000943, 0x00000958, 0x00000965, 0x0000096f,
	0x00000975, 0x0000097d, 0x0000098c, 0x00000993,
	0x000009a1, 0x000009c7, 0x000009d9, 0x000009e1,
	0x000009f6, 0x00000a00, 0x00000a14, 0x00000a1a,
	0x00000a29, 0x00000a43, 0x00000a4c, 0x00000a58,
	// Entry 80 - 9F
	0x00000a5e,
} // Size: 540 bytes

const hu_HUData string = "" + // Size: 2654 bytes
	"\x02Elfogadva\x02Hibás válasz\x02Futási hiba\x02Időlimit túllépés\x02Mem" +
	"órialimit túllépés\x02Belső hiba\x02Nem futott\x02Részben helyes\x02Pre" +
	"zentációs hiba\x02Kihagyva\x02Forditási hiba\x02Fut\x02Feltöltve\x02Bekü" +
	"ldés #%[1]d\x02Archívum\x02Leírás - %[1]s (%[2]s)\x02Eredmények - %[1]s " +
	"(%[2]s)\x02Beküldés - %[1]s (%[2]s)\x02Beküldések - %[1]s (%[2]s)\x02Nin" +
	"cs kategória\x02Feladatok\x02Beküldések\x02Elfelejtett jelszó\x02Megküld" +
	"tük a szükséges további intézkedéseket a megadott email címre (ha regisz" +
	"trálva van a rendszerünkben).\x02Helytelen kulcs.\x02A két megadott jels" +
	"zó nem egyezik meg.\x02A jelszó sikeresen megváltoztatva! Mostmár beléph" +
	"etsz az új jelszavaddal.\x02Már be vagy lépve...\x02Ez a felhasználó fió" +
	"k nincs aktiválva. Ellenőrízd az emailjeid!\x02Sikeres belépés!\x02Hibás" +
	" felhasználónév-jelszó páros!\x02Hibás authentikációs token.\x02A kilépé" +
	"shez előbb lépj be.\x02A név mező kitöltése kötelező.\x02A jelszó mező k" +
	"itöltése kötelező.\x02A jelszó megerősítő mező kitöltése kötelező.\x02Az" +
	" email mező kitöltése kötelező.\x02A név csak alfanumerikus karakterekbő" +
	"l állhat, azaz: betűkből (beleértve a nem latin karaktereket is, pl. 'á'" +
	" vagy 'ű') és számjegyekből.\x02Aktiváld a fiókod\x02Ez a név már foglal" +
	"t.\x02Ez az email cím már foglalt.\x02Köszönjük a regisztrációt! A megad" +
	"ott email címre elküldtük a regisztráció befejezéséhez szükséges végső l" +
	"épéseket.\x02Ez a fiók már aktiválva van.\x02Helytelen aktiválási kulcs" +
	". Biztos vagy benne hogy megfelelő linkre kattintottál?\x02Sikeres aktiv" +
	"álás. Most már beléphetsz!\x02%[1]s profilja\x02%[1]s beküldései\x02Hel" +
	"ytelen régi jelszó.\x02Egy új jelszót meg kell adnod.\x02A két megadott " +
	"jelszó nem egyezik meg.\x02Profil\x02Beállítások\x02Admin\x02Kilépés\x02" +
	"hu\x02Leírás\x02Beküld\x02összes\x02elfogadott\x02Eredmények\x02Bezár" +
	"\x02Információk\x02Azonosító\x02Cím\x02Időlimit\x02Memórialimit\x02IO fá" +
	"jlok\x02Tagek\x02mutasd\x02Típus\x02Szerző\x02Megoldás beküldése\x02Utol" +
	"só beküldések\x02Címke hozzáadása a %[1]q feladathoz\x02Mégse\x02Hozzáad" +
	"\x02Mellékletek\x02Fájl\x02Szerkeszt\x02Leggyorsabb\x02Név\x02Eredmény" +
	"\x02Legkevesebb memória\x02Legkisebb\x02Eredmények\x02Feladat\x02Kód\x02" +
	"Nyelv\x02Kategória\x02Látható\x02Szűrés\x02Szerzőre szűrés?\x02Töröl\x02" +
	"Megoldók\x02Pontok\x02Megoldott feladatok\x02Megpróbált feladatok\x02Rég" +
	"i jelszó\x02Új jelszó\x02Új jelszó mégegyszer\x02Változtat\x02Mutasd a m" +
	"egoldatlan feladatok tag-jeit\x02Ment\x02a %[1]s. teszten\x02Memória\x02" +
	"Idő\x02Program kimenete\x02Elvárt kimenet\x02Ellenőrző kimenete\x02Részf" +
	"eladat\x02Összpont\x02Teszt\x02Verdikt\x02Újraértékel\x02Dátum\x02Felhas" +
	"ználó\x02A következő problémákat találtuk\x02Felhasználónév\x02Jelszó" +
	"\x02Elfelejtett jelszó?\x02Belépés\x02Jelszó mégegyszer\x02Email\x02Regi" +
	"sztráció\x02Jelszó megváltoztatása\x02Főoldal\x02forráskód\x02nyelv"

	// Total table size 6028 bytes (5KiB); checksum: DD80744F
