// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"hu_HU": &dictionary{index: hu_HUIndex, data: hu_HUData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%s on test %d":           58,
	"%s's profile":            44,
	"%s's submissions":        45,
	"Accepted":                0,
	"Activate your account":   40,
	"Add":                     81,
	"Add a tag to problem %q": 79,
	"Admin":                   52,
	"An email with further instructions was sent to the given address (if it's registered in our system).": 22,
	"Archive":                               20,
	"Attachments":                           88,
	"Attempted problems":                    107,
	"Can't logout if you've not logged in.": 32,
	"Cancel":                                80,
	"Category":                              69,
	"Change":                                111,
	"Checker output":                        96,
	"Clear":                                 71,
	"Code":                                  92,
	"Compilation error":                     9,
	"Date":                                  60,
	"Didn't run":                            6,
	"Email":                                 100,
	"Expected output":                       95,
	"File":                                  89,
	"Filter":                                67,
	"Home":                                  49,
	"Identifier":                            72,
	"Information":                           82,
	"Internal error":                        5,
	"Invalid authentication token.":         30,
	"Invalid key provided.":                 23,
	"It's required to give a new password.": 47,
	"Language":                              63,
	"Last submissions":                      87,
	"Login":                                 54,
	"Logout":                                53,
	"Memory":                                66,
	"Memory limit":                          84,
	"Memory limit exceeded":                 4,
	"Name":                                  90,
	"New password":                          109,
	"New password again":                    110,
	"Nickname":                              105,
	"No category":                           17,
	"Old password":                          108,
	"Partially correct":                     7,
	"Password":                              102,
	"Password again":                        103,
	"Password changed succesfully! You can login with your new password.": 25,
	"Password reset":                  21,
	"Points":                          91,
	"Presentation error":              8,
	"Problem":                         62,
	"Problems":                        18,
	"Profile":                         50,
	"Program's output":                94,
	"Ranklist":                        78,
	"Register":                        55,
	"Rejudge":                         93,
	"Reset password":                  101,
	"Results - %s (%s)":               14,
	"Running":                         10,
	"Runtime error":                   2,
	"Save":                            113,
	"Settings":                        51,
	"Show tags for unsolved problems": 112,
	"Solved problems":                 106,
	"Solvers":                         73,
	"Statement":                       74,
	"Statement - %s (%s)":             13,
	"Submission #%d":                  12,
	"Submissions":                     19,
	"Submissions - %s (%s)":           16,
	"Submit":                          75,
	"Submit - %s (%s)":                15,
	"Submit solution":                 86,
	"Subtask":                         97,
	"Successful activation. You can login now!": 43,
	"Successful login!":                         28,
	"Sum":                                       98,
	"Tags":                                      70,
	"Task type":                                 85,
	"Test":                                      99,
	"The account is not activated. Check your emails!": 27,
	"The email field is required.":                     38,
	"The email is already registered.":                 34,
	"The nickname can only consist of alphanumeric characters: letters (including non-latin characters such as 'á' or 'ű') and digits.": 39,
	"The nickname field is required.":              35,
	"The nickname is already registered.":          33,
	"The password confirmation field is required.": 37,
	"The password field is required.":              36,
	"The two given passwords doesn't match.":       48,
	"The two passwords don't match.":               24,
	"This account has already been activated.":     41,
	"Time":                            65,
	"Time limit":                      83,
	"Time limit exceeded":             3,
	"Title":                           68,
	"Uploaded":                        11,
	"User":                            61,
	"Verdict":                         64,
	"We found the following problems": 104,
	"Wrong activation key. Are you sure you've clicked on the right link?": 42,
	"Wrong answer":                1,
	"Wrong credentials.":          29,
	"Wrong old password.":         46,
	"You're already logged in...": 26,
	"Your email is not associated with any registered account.": 31,
	"accepted":   77,
	"all":        76,
	"language":   57,
	"on test %s": 59,
	"source":     56,
}

var en_USIndex = []uint32{ // 115 elements
	// Entry 0 - 1F
	0x00000000, 0x00000009, 0x00000016, 0x00000024,
	0x00000038, 0x0000004e, 0x0000005d, 0x00000068,
	0x0000007a, 0x0000008d, 0x0000009f, 0x000000a7,
	0x000000b0, 0x000000c2, 0x000000dc, 0x000000f4,
	0x0000010b, 0x00000127, 0x00000133, 0x0000013c,
	0x00000148, 0x00000150, 0x0000015f, 0x000001c4,
	0x000001da, 0x000001f9, 0x0000023d, 0x00000259,
	0x0000028a, 0x0000029c, 0x000002af, 0x000002cd,
	// Entry 20 - 3F
	0x00000307, 0x0000032d, 0x00000351, 0x00000372,
	0x00000392, 0x000003b2, 0x000003df, 0x000003fc,
	0x00000480, 0x00000496, 0x000004bf, 0x00000504,
	0x0000052e, 0x0000053e, 0x00000552, 0x00000566,
	0x0000058c, 0x000005b3, 0x000005b8, 0x000005c0,
	0x000005c9, 0x000005cf, 0x000005d6, 0x000005dc,
	0x000005e5, 0x000005ec, 0x000005f5, 0x00000603,
	0x0000060e, 0x00000613, 0x00000618, 0x00000620,
	// Entry 40 - 5F
	0x00000629, 0x00000631, 0x00000636, 0x0000063d,
	0x00000644, 0x0000064a, 0x00000653, 0x00000658,
	0x0000065e, 0x00000669, 0x00000671, 0x0000067b,
	0x00000682, 0x00000686, 0x0000068f, 0x00000698,
	0x000006b0, 0x000006b7, 0x000006bb, 0x000006c7,
	0x000006d2, 0x000006df, 0x000006e9, 0x000006f9,
	0x0000070a, 0x00000716, 0x0000071b, 0x00000720,
	0x00000727, 0x0000072c, 0x00000734, 0x00000745,
	// Entry 60 - 7F
	0x00000755, 0x00000764, 0x0000076c, 0x00000770,
	0x00000775, 0x0000077b, 0x0000078a, 0x00000793,
	0x000007a2, 0x000007c2, 0x000007cb, 0x000007db,
	0x000007ee, 0x000007fb, 0x00000808, 0x0000081b,
	0x00000822, 0x00000842, 0x00000847,
} // Size: 484 bytes

const en_USData string = "" + // Size: 2119 bytes
	"\x02Accepted\x02Wrong answer\x02Runtime error\x02Time limit exceeded\x02" +
	"Memory limit exceeded\x02Internal error\x02Didn't run\x02Partially corre" +
	"ct\x02Presentation error\x02Compilation error\x02Running\x02Uploaded\x02" +
	"Submission #%[1]d\x02Statement - %[1]s (%[2]s)\x02Results - %[1]s (%[2]s" +
	")\x02Submit - %[1]s (%[2]s)\x02Submissions - %[1]s (%[2]s)\x02No categor" +
	"y\x02Problems\x02Submissions\x02Archive\x02Password reset\x02An email wi" +
	"th further instructions was sent to the given address (if it's registere" +
	"d in our system).\x02Invalid key provided.\x02The two passwords don't ma" +
	"tch.\x02Password changed succesfully! You can login with your new passwo" +
	"rd.\x02You're already logged in...\x02The account is not activated. Chec" +
	"k your emails!\x02Successful login!\x02Wrong credentials.\x02Invalid aut" +
	"hentication token.\x02Your email is not associated with any registered a" +
	"ccount.\x02Can't logout if you've not logged in.\x02The nickname is alre" +
	"ady registered.\x02The email is already registered.\x02The nickname fiel" +
	"d is required.\x02The password field is required.\x02The password confir" +
	"mation field is required.\x02The email field is required.\x02The nicknam" +
	"e can only consist of alphanumeric characters: letters (including non-la" +
	"tin characters such as 'á' or 'ű') and digits.\x02Activate your account" +
	"\x02This account has already been activated.\x02Wrong activation key. Ar" +
	"e you sure you've clicked on the right link?\x02Successful activation. Y" +
	"ou can login now!\x02%[1]s's profile\x02%[1]s's submissions\x02Wrong old" +
	" password.\x02It's required to give a new password.\x02The two given pas" +
	"swords doesn't match.\x02Home\x02Profile\x02Settings\x02Admin\x02Logout" +
	"\x02Login\x02Register\x02source\x02language\x02%s on test %d\x02on test " +
	"%s\x02Date\x02User\x02Problem\x02Language\x02Verdict\x02Time\x02Memory" +
	"\x02Filter\x02Title\x02Category\x02Tags\x02Clear\x02Identifier\x02Solver" +
	"s\x02Statement\x02Submit\x02all\x02accepted\x02Ranklist\x02Add a tag to " +
	"problem %q\x02Cancel\x02Add\x02Information\x02Time limit\x02Memory limit" +
	"\x02Task type\x02Submit solution\x02Last submissions\x02Attachments\x02F" +
	"ile\x02Name\x02Points\x02Code\x02Rejudge\x02Program's output\x02Expected" +
	" output\x02Checker output\x02Subtask\x02Sum\x02Test\x02Email\x02Reset pa" +
	"ssword\x02Password\x02Password again\x02We found the following problems" +
	"\x02Nickname\x02Solved problems\x02Attempted problems\x02Old password" +
	"\x02New password\x02New password again\x02Change\x02Show tags for unsolv" +
	"ed problems\x02Save"

var hu_HUIndex = []uint32{ // 115 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000a, 0x00000019, 0x00000026,
	0x0000003c, 0x00000056, 0x00000062, 0x0000006d,
	0x0000007d, 0x00000091, 0x000000a1, 0x000000a5,
	0x000000b0, 0x000000c2, 0x000000db, 0x000000f7,
	0x0000010f, 0x0000012c, 0x0000013d, 0x00000147,
	0x00000154, 0x0000015e, 0x00000172, 0x000001e9,
	0x000001fa, 0x00000223, 0x00000267, 0x0000027e,
	0x000002c4, 0x000002d7, 0x00000300, 0x0000031f,
	// Entry 20 - 3F
	0x0000035b, 0x0000037b, 0x00000393, 0x000003b2,
	0x000003d7, 0x000003ff, 0x00000435, 0x0000045c,
	0x000004f1, 0x00000505, 0x00000525, 0x0000057b,
	0x000005a7, 0x000005b6, 0x000005c9, 0x000005e2,
	0x00000603, 0x0000062c, 0x00000635, 0x0000063c,
	0x0000064b, 0x00000651, 0x0000065b, 0x00000665,
	0x00000674, 0x00000680, 0x00000686, 0x0000069e,
	0x000006b2, 0x000006b9, 0x000006c7, 0x000006cf,
	// Entry 40 - 5F
	0x000006d5, 0x000006dd, 0x000006e2, 0x000006eb,
	0x000006f4, 0x000006f9, 0x00000704, 0x0000070a,
	0x00000712, 0x0000071e, 0x00000728, 0x00000731,
	0x00000739, 0x00000741, 0x0000074c, 0x00000758,
	0x00000779, 0x00000780, 0x00000789, 0x00000797,
	0x000007a1, 0x000007af, 0x000007b6, 0x000007cc,
	0x000007e1, 0x000007ee, 0x000007f4, 0x000007f9,
	0x00000800, 0x00000805, 0x00000814, 0x00000825,
	// Entry 60 - 7F
	0x00000835, 0x00000849, 0x00000856, 0x00000860,
	0x00000866, 0x0000086c, 0x00000886, 0x0000088e,
	0x000008a2, 0x000008c8, 0x000008da, 0x000008ee,
	0x00000905, 0x00000913, 0x0000091f, 0x00000937,
	0x00000942, 0x0000096a, 0x0000096f,
} // Size: 484 bytes

const hu_HUData string = "" + // Size: 2415 bytes
	"\x02Elfogadva\x02Hibás válasz\x02Futási hiba\x02Időlimit túllépés\x02Mem" +
	"órialimit túllépés\x02Belső hiba\x02Nem futott\x02Részben helyes\x02Pre" +
	"zentációs hiba\x02Forditási hiba\x02Fut\x02Feltöltve\x02Beküldés #%[1]d" +
	"\x02Leírás - %[1]s (%[2]s)\x02Eredmények - %[1]s (%[2]s)\x02Beküld - %[1" +
	"]s (%[2]s)\x02Beküldések - %[1]s (%[2]s)\x02Nincs kategória\x02Feladatok" +
	"\x02Beküldések\x02Archívum\x02Elfelejtett jelszó\x02Megküldtük a szükség" +
	"es további intézkedéseket a megadott email címre (ha regisztrálva van a " +
	"rendszerünkben).\x02Helytelen kulcs.\x02A két megadott jelszó nem egyezi" +
	"k meg.\x02Jelszó sikeresen megváltoztatva! Beléphetsz az új jelszavaddal" +
	".\x02Már be vagy lépve...\x02Ez a felhasználó fiók nincs aktiválva. Elle" +
	"nőrízd az emailjeid!\x02Sikeres belépés!\x02Hibás felhasználónév-jelszó " +
	"páros!\x02Hibás authentikációs token.\x02Az email címed nem tartozik egy" +
	" regisztrált fiókhoz sem.\x02A kilépéshez előbb lépj be.\x02Ez a név már" +
	" foglalt.\x02Ez az email cím már foglalt.\x02A név mező kitöltése kötele" +
	"ző.\x02A jelszó mező kitöltése kötelező.\x02A jelszó megerősítő mező kit" +
	"öltése kötelező.\x02Az email mező kitöltése kötelező.\x02A név csak alf" +
	"anumerikus karakterekből állhat, azaz: betűkből (beleértve a nem latin k" +
	"araktereket is, pl. 'á' vagy 'ű') és számjegyekből.\x02Aktiváld a fiókod" +
	"\x02Ez a fiók már aktiválva van.\x02Helytelen aktiválási kulcs. Biztos v" +
	"agy benne hogy megfelelő linkre kattintottál?\x02Sikeres aktiválás. Most" +
	" már beléphetsz!\x02%[1]s profilja\x02%[1]s beküldései\x02Helytelen régi" +
	" jelszó.\x02Egy új jelszót meg kell adnod.\x02A két megadott jelszó nem " +
	"egyezik meg.\x02Főoldal\x02Profil\x02Beállítások\x02Admin\x02Kilépés\x02" +
	"Belépés\x02Regisztráció\x02forráskód\x02nyelv\x02%s a(z) %d. teszteseten" +
	"\x02a(z) %d. tesztesten\x02Dátum\x02Felhasználó\x02Feladat\x02Nyelv\x02V" +
	"erdikt\x02Idő\x02Memória\x02Szűrés\x02Cím\x02Kategória\x02Tagek\x02Töröl" +
	"\x02Azonosító\x02Megoldók\x02Leírás\x02Beküld\x02összes\x02elfogadott" +
	"\x02Eredmények\x02Tag hozzáadása a %q feladathoz\x02Mégse\x02Hozzáad\x02" +
	"Információk\x02Időlimit\x02Memórialimit\x02Típus\x02Megoldás beküldése" +
	"\x02Utolsó beküldések\x02Mellékletek\x02Fájl\x02Név\x02Pontok\x02Kód\x02" +
	"Újraértékel\x02Program kimenete\x02Elvárt kimenet\x02Ellenőrző kimenet" +
	"\x02Részfeladat\x02Összpont\x02Teszt\x02Email\x02Jelszó megváltoztatása" +
	"\x02Jelszó\x02Jelszó mégegyszer\x02A következő problémákat találtuk\x02F" +
	"elhasználónév\x02Megoldott feladatok\x02Megpróbált feladatok\x02Régi jel" +
	"szó\x02Új jelszó\x02Új jelszó mégegyszer\x02Változtat\x02Mutasd a megold" +
	"atlan feladatok tag-jeit\x02Ment"

	// Total table size 5502 bytes (5KiB); checksum: 8538161F
