// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"hu_HU": &dictionary{index: hu_HUIndex, data: hu_HUData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%s's profile":                          28,
	"%s's submissions":                      29,
	"Activate your account":                 24,
	"Admin":                                 32,
	"Archive":                               8,
	"Can't logout if you've not logged in.": 15,
	"Home":                                  30,
	"Invalid authentication token.":         13,
	"Login":                                 34,
	"Logout":                                33,
	"No category":                           5,
	"Problems":                              6,
	"Profile":                               31,
	"Register":                              35,
	"Results - %s (%s)":                     2,
	"Statement - %s (%s)":                   1,
	"Submission #%d":                        0,
	"Submissions":                           7,
	"Submissions - %s (%s)":                 4,
	"Submit - %s (%s)":                      3,
	"Successful activation. You can login now!":        27,
	"Successful login!":                                11,
	"The account is not activated. Check your emails!": 10,
	"The email field is required.":                     21,
	"The email is already registered.":                 17,
	"The nickname can only consist of alphanumeric characters: letters (including non-latin characters such as 'á' or 'ű') and digits.": 22,
	"The nickname field is required.":                                      18,
	"The nickname is already registered.":                                  16,
	"The password confirmation field is required.":                         20,
	"The password field is required.":                                      19,
	"The two passwords don't match.":                                       23,
	"This account has already been activated.":                             25,
	"Wrong activation key. Are you sure you've clicked on the right link?": 26,
	"Wrong credentials.":                                                   12,
	"You're already logged in...":                                          9,
	"Your email is not associated with any registered account.":            14,
	"language": 37,
	"source":   36,
}

var en_USIndex = []uint32{ // 39 elements
	// Entry 0 - 1F
	0x00000000, 0x00000012, 0x0000002c, 0x00000044,
	0x0000005b, 0x00000077, 0x00000083, 0x0000008c,
	0x00000098, 0x000000a0, 0x000000bc, 0x000000ed,
	0x000000ff, 0x00000112, 0x00000130, 0x0000016a,
	0x00000190, 0x000001b4, 0x000001d5, 0x000001f5,
	0x00000215, 0x00000242, 0x0000025f, 0x000002e3,
	0x00000302, 0x00000318, 0x00000341, 0x00000386,
	0x000003b0, 0x000003c0, 0x000003d4, 0x000003d9,
	// Entry 20 - 3F
	0x000003e1, 0x000003e7, 0x000003ee, 0x000003f4,
	0x000003fd, 0x00000404, 0x0000040d,
} // Size: 180 bytes

const en_USData string = "" + // Size: 1037 bytes
	"\x02Submission #%[1]d\x02Statement - %[1]s (%[2]s)\x02Results - %[1]s (%" +
	"[2]s)\x02Submit - %[1]s (%[2]s)\x02Submissions - %[1]s (%[2]s)\x02No cat" +
	"egory\x02Problems\x02Submissions\x02Archive\x02You're already logged in." +
	"..\x02The account is not activated. Check your emails!\x02Successful log" +
	"in!\x02Wrong credentials.\x02Invalid authentication token.\x02Your email" +
	" is not associated with any registered account.\x02Can't logout if you'v" +
	"e not logged in.\x02The nickname is already registered.\x02The email is " +
	"already registered.\x02The nickname field is required.\x02The password f" +
	"ield is required.\x02The password confirmation field is required.\x02The" +
	" email field is required.\x02The nickname can only consist of alphanumer" +
	"ic characters: letters (including non-latin characters such as 'á' or 'ű" +
	"') and digits.\x02The two passwords don't match.\x02Activate your accoun" +
	"t\x02This account has already been activated.\x02Wrong activation key. A" +
	"re you sure you've clicked on the right link?\x02Successful activation. " +
	"You can login now!\x02%[1]s's profile\x02%[1]s's submissions\x02Home\x02" +
	"Profile\x02Admin\x02Logout\x02Login\x02Register\x02source\x02language"

var hu_HUIndex = []uint32{ // 39 elements
	// Entry 0 - 1F
	0x00000000, 0x00000012, 0x0000002b, 0x00000047,
	0x0000005f, 0x0000007c, 0x0000008d, 0x00000097,
	0x000000a4, 0x000000ae, 0x000000c5, 0x0000010b,
	0x0000011e, 0x00000147, 0x00000166, 0x000001a2,
	0x000001c2, 0x000001da, 0x000001f9, 0x0000021e,
	0x00000246, 0x0000027c, 0x000002a3, 0x00000338,
	0x00000361, 0x00000375, 0x00000395, 0x000003eb,
	0x00000417, 0x00000426, 0x00000439, 0x00000442,
	// Entry 20 - 3F
	0x00000449, 0x0000044f, 0x00000459, 0x00000463,
	0x00000472, 0x0000047e, 0x00000484,
} // Size: 180 bytes

const hu_HUData string = "" + // Size: 1156 bytes
	"\x02Beküldés #%[1]d\x02Leírás - %[1]s (%[2]s)\x02Eredmények - %[1]s (%[2" +
	"]s)\x02Beküld - %[1]s (%[2]s)\x02Beküldések - %[1]s (%[2]s)\x02Nincs kat" +
	"egória\x02Feladatok\x02Beküldések\x02Archívum\x02Már be vagy lépve..." +
	"\x02Ez a felhasználó fiók nincs aktiválva. Ellenőrízd az emailjeid!\x02S" +
	"ikeres belépés!\x02Hibás felhasználónév-jelszó páros!\x02Hibás authentik" +
	"ációs token.\x02Az email címed nem tartozik egy regisztrált fiókhoz sem" +
	".\x02A kilépéshez előbb lépj be.\x02Ez a név már foglalt.\x02Ez az email" +
	" cím már foglalt.\x02A név mező kitöltése kötelező.\x02A jelszó mező kit" +
	"öltése kötelező.\x02A jelszó megerősítő mező kitöltése kötelező.\x02Az " +
	"email mező kitöltése kötelező.\x02A név csak alfanumerikus karakterekből" +
	" állhat, azaz: betűkből (beleértve a nem latin karaktereket is, pl. 'á' " +
	"vagy 'ű') és számjegyekből.\x02A két megadott jelszó nem egyezik meg." +
	"\x02Aktiváld a fiókod\x02Ez a fiók már aktiválva van.\x02Helytelen aktiv" +
	"álási kulcs. Biztos vagy benne hogy megfelelő linkre kattintottál?\x02S" +
	"ikeres aktiválás. Most már beléphetsz!\x02%[1]s profilja\x02%[1]s beküld" +
	"ései\x02Főoldal\x02Profil\x02Admin\x02Kilépés\x02Belépés\x02Regisztráci" +
	"ó\x02forráskód\x02nyelv"

	// Total table size 2553 bytes (2KiB); checksum: 9D3892C7
